"""add_audio_clip_path_to_job_shots

Revision ID: 3352a9b29fc1
Revises: 6c63165cf4b1
Create Date: 2026-03-07 18:35:02.917891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3352a9b29fc1'
down_revision: Union[str, Sequence[str], None] = '6c63165cf4b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_shots', sa.Column('audio_clip_path', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_shots', 'audio_clip_path')
    # ### end Alembic commands ###
