"""add title to jobs

Revision ID: 3bcf0cfdde97
Revises: 3352a9b29fc1
Create Date: 2026-03-07 20:59:06.670051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bcf0cfdde97'
down_revision: Union[str, Sequence[str], None] = '3352a9b29fc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add column as nullable
    op.add_column('jobs', sa.Column('title', sa.String(length=255), nullable=True))
    
    # Update existing rows: fallback to product_name
    op.execute("UPDATE jobs SET title = product_name WHERE title IS NULL")
    
    # Alter column to be not null
    op.alter_column('jobs', 'title', existing_type=sa.String(length=255), nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'title')
    # ### end Alembic commands ###
