"""initial migration

Revision ID: 814223b98cff
Revises: 
Create Date: 2026-03-01 01:25:18.613400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '814223b98cff'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('target_audience', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RESEARCHING', 'DIRECTING', 'GENERATING', 'ASSEMBLING', 'DONE', 'FAILED', name='jobstatus'), nullable=False),
    sa.Column('progress_message', sa.Text(), nullable=True),
    sa.Column('total_shots', sa.Integer(), nullable=False),
    sa.Column('completed_shots', sa.Integer(), nullable=False),
    sa.Column('final_video_path', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    # ### end Alembic commands ###
