"""initial migration

Revision ID: 9e22c96d63e2
Revises: 
Create Date: 2026-03-07 02:31:36.016997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e22c96d63e2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('product_research', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RESEARCHING', 'DIRECTING', 'GENERATING_IMAGES', 'AWAITING_SELECTION', 'GENERATING_VIDEOS', 'ASSEMBLING', 'DONE', 'FAILED', 'CANCELLED', 'REJECTED', name='jobstatus'), nullable=False),
    sa.Column('progress_message', sa.Text(), nullable=True),
    sa.Column('total_shots', sa.Integer(), nullable=False),
    sa.Column('completed_shots', sa.Integer(), nullable=False),
    sa.Column('final_video_path', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_shots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('shot_index', sa.Integer(), nullable=False),
    sa.Column('shot_type', sa.String(length=50), nullable=False),
    sa.Column('camera_angle', sa.String(length=100), nullable=True),
    sa.Column('camera_movement', sa.String(length=255), nullable=True),
    sa.Column('subject_action', sa.Text(), nullable=True),
    sa.Column('lighting', sa.String(length=255), nullable=True),
    sa.Column('emotion', sa.String(length=100), nullable=True),
    sa.Column('voiceover_text', sa.Text(), nullable=True),
    sa.Column('image_prompt', sa.Text(), nullable=True),
    sa.Column('video_prompt', sa.Text(), nullable=True),
    sa.Column('negative_prompt', sa.Text(), nullable=True),
    sa.Column('scene_image_path', sa.Text(), nullable=True),
    sa.Column('scene_image_path_2', sa.Text(), nullable=True),
    sa.Column('selected_image', sa.Integer(), nullable=True),
    sa.Column('video_clip_path', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'GENERATING', 'DONE', 'FAILED', name='jobshotstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_shots')
    op.drop_table('jobs')
    # ### end Alembic commands ###
