"""add_character_image_path_to_jobs

Revision ID: c1017d84183b
Revises: 1b115ea85d33
Create Date: 2026-03-07 16:05:56.867983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1017d84183b'
down_revision: Union[str, Sequence[str], None] = '1b115ea85d33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('character_image_path', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'character_image_path')
    # ### end Alembic commands ###
