"""Add JobShot table and product_research

Revision ID: d46496c637d1
Revises: 98cf983cb5e0
Create Date: 2026-03-01 19:55:24.220930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd46496c637d1'
down_revision: Union[str, Sequence[str], None] = '98cf983cb5e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_shots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('shot_index', sa.Integer(), nullable=False),
    sa.Column('shot_type', sa.String(length=50), nullable=False),
    sa.Column('camera_angle', sa.String(length=100), nullable=True),
    sa.Column('camera_movement', sa.String(length=255), nullable=True),
    sa.Column('subject_action', sa.Text(), nullable=True),
    sa.Column('lighting', sa.String(length=255), nullable=True),
    sa.Column('emotion', sa.String(length=100), nullable=True),
    sa.Column('voiceover_text', sa.Text(), nullable=True),
    sa.Column('image_prompt', sa.Text(), nullable=True),
    sa.Column('video_prompt', sa.Text(), nullable=True),
    sa.Column('scene_image_path', sa.Text(), nullable=True),
    sa.Column('video_clip_path', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'GENERATING', 'DONE', 'FAILED', name='jobshotstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('jobs', sa.Column('product_research', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'product_research')
    op.drop_table('job_shots')
    # ### end Alembic commands ###
